// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstxZH0OLGTi8-0bD_CnzZq1e61hvFtHo',
    appId: '1:271408880910:web:b7e8b5aa9d2cbc1314cb5f',
    messagingSenderId: '271408880910',
    projectId: 'lukes-picks',
    authDomain: 'lukes-picks.firebaseapp.com',
    storageBucket: 'lukes-picks.firebasestorage.app',
    measurementId: 'G-91GLRM1JLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjoktEShP6Qw_SRXjnIhAyBX7zyQEtjJw',
    appId: '1:271408880910:android:a99dd01fb4d5bb8114cb5f',
    messagingSenderId: '271408880910',
    projectId: 'lukes-picks',
    storageBucket: 'lukes-picks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDj9YKaq6Nl9_PihLQYYYGRYfYCxFWGIg',
    appId: '1:271408880910:ios:dd22577f5d50ef1f14cb5f',
    messagingSenderId: '271408880910',
    projectId: 'lukes-picks',
    storageBucket: 'lukes-picks.firebasestorage.app',
    iosBundleId: 'com.mleikam.lukespics',
  );
}
